default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  username: postgres

development:
  <<: *default
  database: debugme_development

test:
  <<: *default
  database: debugme_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: debugme_production
